image: golang

before_script:
  - mkdir -p /go/src/github.com/KingCrunch/ && cp -ar /builds/Golang/mocksmtp /go/src/github.com/KingCrunch/mocksmtp

test:
  script:
    - make -C /go/src/github.com/KingCrunch/mocksmtp test
